#!/usr/bin/env bash

SWITCH=$1

source colors.sh

if [ -z "$SWITCH" ]; then
	echo "Usage:"
	echo "aruba_loopprotect switch_ip"
	echo "aruba_loopprotect 192.168.3.12"
	return 1 2>&- || exit
fi

. aruba_auth

NEIGHBORS=$(aruba_command $SWITCH sh lldp info remote-device :: sh cdp neighbors | grep -P '[0-9]')
PORTS=$(echo "$NEIGHBORS" | awk '{print $1}' |  sort -V -u)
echo "$PORTS"


# customize with your own.
options=("AAA" "BBB" "CCC" "DDD")

menu() {
	echo "Avaliable options:"
	for i in ${!options[@]}; do
		printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
	done
	if [[ "$msg" ]]; then echo "$msg"; fi
}

choose() {
	prompt="Check an option (again to uncheck, ENTER when done): "
	while menu && read -rp "$prompt" num && [[ "$num" ]]; do
		[[ "$num" != *[![:digit:]]* ]] &&
		(( num > 0 && num <= ${#options[@]} )) ||
		{ msg="Invalid option: $num"; continue; }
		((num--)); msg="${options[num]} was ${choices[num]:+un}checked"
		[[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
	done

	printf "You selected"; msg=" nothing"
	for i in ${!options[@]}; do
		[[ "${choices[i]}" ]] && { printf " %s" "${options[i]}"; msg=""; }
	done
	echo "$msg"
}
