#!/usr/bin/env bash

SWITCH=$1

if [ -z "$SWITCH" ]; then
	echo "aruba_model returns the model of the switch. Usage:"
	echo "aruba_model switch_ip"
	echo "aruba_model 192.168.3.12"
	return 1 2>&- || exit
fi

SNMP_RO_COMMUNITY="public"
[ -n $(command -v pktools_vars) ] && . pktools_vars

MODEL=$(timeout 1 snmpget -v2c -c$SNMP_RO_COMMUNITY 10.95.64.11 1.3.6.1.2.1.1.1.0 -Oe 2>&- | sed -E 's/.*STRING: //')
if [ -z "$MODEL" ]; then
	. aruba_auth
	MODEL=$(aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$' | sed -E 's/^[^=]+ *= *//')
fi

echo -n "$SWITCH: "
[ -n "$MODEL" ] && echo "$MODEL" || echo "Could not determine model"
