#!/usr/bin/env bash

if [ -z "$ARUBA_COMMAND_PASS" ]; then
	if [ ! -t 1 ] || [ ! -t 0 ]; then
		# stdout isn't a terminal
		echo "There are no cached credentials. Please run '. aruba_command' alone to cache them."
		return 2>&-
		exit 1
	fi

	>&2 echo "If you source this file you credentials will be cached in memory for this shell only"
	
	if [ -z $ARUBA_COMMAND_USER ]; then
		>&2 echo -n 'Username: '
		read ARUBA_COMMAND_USER
	fi
	
	>&2 echo -n 'Password: '
	read -s ARUBA_COMMAND_PASS
	>&2 echo
	>&2 echo
fi

export ARUBA_COMMAND_USER
export ARUBA_COMMAND_PASS
