#!/usr/bin/env bash

SCRIPT="$(basename "$0")"

function help() {
	cat <<-EOF

		$SCRIPT [-l|--long] switch_IPs
		  -l or --long shows full info that is not needed most of the time
	
		Usage example:
		  $SCRIPT returns the model of the switch. Usage:
		  $SCRIPT 192.168.3.11 192.168.3.12

	EOF
	return 1 2>&- || exit 1
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-l|--long)
	LONG="--long"
	shift # past argument
	;;
	-h|--help)
		help
	;;
	*)    # unknown option
	POSITIONAL+=("$1") # save it in an array for later
	shift # past argument
	;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

[ -t 0 ] && [ -z "$*" ] && help

while read SWITCH; do
	MODEL=$(snmp_model "$LONG" $SWITCH)
	if [ -z "$MODEL" ]; then
		. aruba_auth
		MODEL=$(aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$|^.$' | sed -E 's/^[^=]+ *= *//')
	fi
	[ -z "$LONG" ] && MODEL=$(sed -E 's|\(/ws/[^)]+\)\)||g;s|\(Formerly ProCurve\)||g' <<< "$MODEL")

	echo -n "$SWITCH: "
	[ -n "$MODEL" ] && echo "$MODEL" || echo "Could not determine model"
done < <([ -n "$*" ] && tr ' ' '\n' <<< $* ; [ ! -t 0 ] && cat)
