#!/usr/bin/env bash

SWITCH=$1

if [ -z "$SWITCH" ]; then
	echo "aruba_model returns the model of the switch. Usage:"
	echo "aruba_model switch_ip"
	echo "aruba_model 192.168.3.12"
	return 1 2>&- || exit
fi

. aruba_auth

aruba_command $SWITCH "getmib 1.3.6.1.2.1.1.1.0" | grep -Pv '^\s*$' | sed -E 's/^[^=]+ *= *//'
