#!/usr/bin/env bash

DIR="$HOME/Downloads/CB_Malware_Binaries"
BIN=$(ls -tr ~/Downloads/????????-????-????-????-???????????? | tail -n 1)

echo "Original cb get download detected is $BIN"
ls -l "$BIN"
file "$BIN"

[ ! -d "$DIR" ] && echo $DIR does not exist. Exiting. && exit 1

while [ -z "$FILENAME" ]; do
	echo -n "Enter original filename: "
	read FILENAME
done

FILE="$DIR/$FILENAME"
mkdir "$DIR" &>/dev/null
touch "$DIR"
mv "$BIN" "$FILE"

if [ "$?" -ne 0 ]; then
	echo "Could not rename $BIN to $FILE"
fi

virustotal_scan $FILE

REMOVE="?"
while [[ ! "$REMOVE" =~ ^(y|n|Y|N|)$ ]]; do
	echo -n "Remove $BIN and $FILE? Default: y (y|n): "
	REMOVE="y"
	read -n1 REMOVE
	echo
done
[[ "$REMOVE" =~ ^(y|Y|)$ ]] && echo "Removing $BIN and $FILE" && rm "$BIN" "$FILE"
