#!/usr/bin/env bash

if [ -z "$CISCO_SHOWRUNN_PASS" ]; then
	if [ ! -t 1 ] || [ ! -t 0 ]; then
		# stdout isn't a terminal
		echo "There are no cached credentials. Please run '. cisco_command' alone to cache them."
		return 2>&-
		exit 1
	fi

	>&2 echo "If you source this file you credentials will be cached in memory for this shell only"
	
	>&2 echo -n 'Password: '
	read -s CISCO_SHOWRUNN_PASS
	export CISCO_SHOWRUNN_PASS
	>&2 echo
	>&2 echo -n 'Enable: '
	read -s CISCO_SHOWRUNN_ENABLE
	export CISCO_SHOWRUNN_ENABLE
	>&2 echo
	>&2 echo
fi
