#!/usr/bin/env bash

TMP=/tmp
CMD=cisco_showrunn
CACHE_EXPIRE_MIN=5

PARAMS=""
for i in $(seq $#); do
  case "$1" in
    -f|--force)
      FORCE=FORCE
      shift
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

if [ -z "$CISCO_SHOWRUNN_PASS" ]; then
	>&2 echo "If you source this file you credentials will be cached in memory for this shell only"
	
	>&2 echo -n 'Password: '
	read -s CISCO_SHOWRUNN_PASS
	export CISCO_SHOWRUNN_PASS
	>&2 echo
	>&2 echo -n 'Enable: '
	read -s CISCO_SHOWRUNN_ENABLE
	export CISCO_SHOWRUNN_ENABLE
	>&2 echo
fi

export DEVICE=$1
export PASS="$CISCO_SHOWRUNN_PASS"
export ENABLE="$CISCO_SHOWRUNN_ENABLE"

SUM=$(echo -n $DEVICE | sha1sum | cut -d\  -f1)
CACHE=$TMP/cache-$SUM.$CMD
GLOB=cache-*.$CMD

find $TMP -maxdepth 1 -iname $GLOB -mmin +$CACHE_EXPIRE_MIN -exec rm {} \;

function getConfig {
	[ -f "$CACHE" ] && cat "$CACHE" && return 0
	cisco_command $DEVICE show runn 
	[ -z "$CFG" ] || echo "$CFG" > $CACHE
	echo "$CFG"
}

CFG="$(getConfig)"
echo "$CFG"
