#!/usr/bin/env bash

SCRIPT_PATH="$(realpath "$0")"
SCRIPT="$(basename "$SCRIPT_PATH")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

SLEEP=${1:-2}

require_commands xclip xdotool || exit 1

XDOTOOL=$(which xdotool)
XCLIP=$(which xclip)

TEXT=$($XCLIP -out -selection clipboard)

if [ "$TEXT" == "" ]; then
    exit;
fi

sleep $SLEEP

#ACTIVEWIN=$($XDOTOOL getactivewindow)
#if [ "$ACTIVEWIN" == "" ]; then
#    exit;
#fi

#$XDOTOOL type --window $ACTIVEWIN "$TEXT"
$XDOTOOL type "$TEXT"
