#!/usr/bin/env bash

if [ "$#" -eq 1 ] && [ "$1" == "--help" ]; then
	echo 'clipboard allows you to send text to the xwindows cliboard or get text from it.'
	echo 'To get contents: clipboard'
	echo 'To set contents: echo some text > clipboard'
	exit
fi

if [ -t 0 ]; then
	if [ "$#" -eq 0 ]; then
		xclip -out -selection clipboard
	else
		xclip -in -selection clipboard <<< "$*"
	fi
else
	xclip -in -selection clipboard <&0
fi
