#!/usr/bin/env bash

SCRIPT="$(basename "$0")"

require_commands unbuffer whois colorize || exit 1

function help() {
	cat <<-EOF

		$SCRIPT Provides whois information
	
		Usage example:
		  $SCRIPT domain_name

	EOF
	exit 1
}

function on_exit() {
	: # Your cleanup code here
}
trap on_exit EXIT

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-v|--param-with-value)
	PARAM_VALUE="$2"
	shift # past argument
	shift # past value
	;;
	-h|--help)
	help
	shift # past argument
	;;
	-p|--param-only)
	PARAM_ONLY="YES"
	shift # past argument
	;;
	*) # unknown option
	POSITIONAL+=("$1") # save it in an array for later
	shift # past argument
	;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

ITEM=$1

[ -z "$ITEM" ] && help

unbuffer whois $ITEM | grep -P 'Date|Created On:|Last Updated On:' | sed -E 's/^\s+//g' | colorize red 'Creat.*: (.*)' blue '.*: (.*)' 
