#!/usr/bin/env bash

SCRIPT="$(basename "$0")"

function help() {
	cat <<-EOF

		$SCRIPT lists disk usage at the current directory
		$SCRIPT -x lists disk usage at the current directory skipping mounts / other filesystems
	
		Usage example:
		  $SCRIPT $_example_usage_

	EOF
	exit 1
}

grep -Piq -- '--help|-h' <<< $* && help

du -sh $* $(ls -A) | sort -h

#LIST="$(find -maxdepth 1 2>&- | grep -Pv '^\.$')"
#while read -r FILE; do
#	du -sh "$FILE" 2>&-
#done <<< "$LIST" | sed -E 's|(^[^ ]+)\t\./(.*)|\1\t\2|g' | sort -h
