#!/usr/bin/env bash

SCRIPT="$(basename "$0")"

function help() {
	cat <<-EOF

		$SCRIPT lists disk usage at the current directory
	
		Usage example:
		  $SCRIPT $_example_usage_

	EOF
	exit 1
}

grep -Piq -- '--help|-h' <<< $* && help


LIST="$(find -maxdepth 1 | grep -Pv '^\.$')"
while read -r FILE; do
	du -sh "$FILE"
done <<< "$LIST" | sed -E 's|(^[^ ]+)\t\./(.*)|\1\t\2|g' | sort -h
