#!/usr/bin/env bash


SCRIPT=$(basename $0)
OLD="/tmp/old_$SCRIPT"
TMP="/tmp/$SCRIPT-$(date "+%Y-%m-%d--%H-%M-%S")"

function finish {
	[ -d "$TMP" ] && rm -rf "$TMP"
}

function show_tips {
	echo "Usefull tools:"
	echo "  olevba <office file>"
	echo "  peepdf -i -f <pdf file>"
	echo "	  Look for a line:"
	echo "      Objects with JS code (num): [obj_nums array]"
	echo "      and inspect them:"
	echo "      js_analyse object <number of object with JS code if any found>"
	echo
}

trap finish EXIT

mkdir "$TMP"

ORIG_FILE="$TMP/original_message"
TMP_ORIG_FILE="$ORIG_FILE.tmp"

echo "Paste email source or curl command. ctrl-d when done" | grep -P "ctrl-d|$" --color=auto
DATA=$(cat)
if [[ "$DATA" =~ ^curl\  ]]; then
	URL=$( ( sed -E 's/\|.*//;s/\\//g' | tr -d '\n' ) <<< "$DATA")
	# Use recode to decode html escaped characters 
	eval $URL -o "$TMP_ORIG_FILE"
	#cat "$TMP_ORIG_FILE" | grep ',"Delivered-To:' | perl -pe 's/.*,"(Delivered-To:.*)"], .*/$1/g' | sed -e 's/\\r\\n/\n/g;s/\\"/"/g' | recode -f html..ascii > $ORIG_FILE
	cat "$TMP_ORIG_FILE" | grep ',"Delivered-To:' | perl -pe 's/.*,"(Delivered-To:.*)"], .*/{"data":"$1"}/g' | jq -r '.data' > $ORIG_FILE
	rm "$TMP_ORIG_FILE"
else
	echo "$DATA" > $ORIG_FILE
fi

ripmime -d "$TMP" --paranoid -v -i - < "$ORIG_FILE"

echo DONE. Files extracted in "$TMP"
ls -lh "$TMP"

#xdg-open "$TMP" &
show_tips
cd "$TMP"
$SHELL
