#!/usr/bin/env bash

SCRIPT=$(basename $0)
#TMP="/tmp/$SCRIPT"; mkdir "$TMP" 2>&-
TMP=$(mktemp -d /tmp/$SCRIPT.XXXXXXXX)

function finish {
	[ -d "$TMP" ] && ( rm "$TMP/*"; rmdir "$TMP" ) 2>&-
}
trap finish EXIT

echo "Paste email source. ctrl-d when done" | grep -P "ctrl-d|$" --color=auto
DATA=$(cat)

ripmime -d "$TMP" --paranoid -v -i - <<< "$DATA"

OIFS="$IFS"
IFS=$'\n'
for FILE in $(find "$TMP" -type f | grep -Pv 'textfile\d+'); do
	virustotal_scan $FILE
done
IFS="$OIFS"
