#!/bin/bash
SEARCH="$1"
[ -z "$SEARCH" ] && SEARCH="^"
MATCHES=$(gam print groups 2>/dev/null | grep -v '^Email$' | grep -Pi "$SEARCH")
MATCHNUM=$(echo -n "$MATCHES" | grep "^" -c)

[ -z "$SEARCH" ] || SPHRASE="for '$SEARCH'"
[ $MATCHNUM -eq 0 ] && echo No Matches $SPHRASE
[ $MATCHNUM -eq 1 ] && gam info group "$MATCHES" | ack --passthru -i "$SEARCH"
[ $MATCHNUM -gt 1 ] && echo "$MATCHES" | ack --passthru -i "$SEARCH"

