#!/usr/bin/env bash
#This is a simple greenpages cli client with offline capability

. colors.sh

UPDATE_TIMEOUT=30 #in tens of milliseconds. 20=200ms
CONNECT_TIMEOUT=10 #Server connect timeout in seconds
GPURI="http://gpapi.parkdalemills.com/cli"
GPDATA=~/.greenpages
GPDATATEMP="$(mktemp -u $GPDATA-XXXXXXXX)"

[ -f "$GPDATA" ] && CACHED=yes

function getData {
	curl --connect-timeout 10 -s "$GPURI" -o "$GPDATATEMP" 2>$-
	mv "$GPDATATEMP" "$GPDATA" 2>&- && touch "$GPDATA"
}

function finish {
	rm "$GPDATATEMP" 2>&-
}

trap finish EXIT

FIELDS=()
SEARCH=$*
IFS_ORIG="$IFS"

function getFields {
	read -r -a HEADER <<< $(head -n 1 "$GPDATA")
	IFS='|' 
	for FIELD in $HEADER; do
		FIELDS+=($FIELD)
	done
	export FIELDS
}

function gp {
	tail -n +2 "$GPDATA"
}

function clearLastLine {
	tput cuu 1 && tput el
}

function formatEntry {
	local LINENUM=0
	IFS="|"
	while read LINE; do
		[ "$LINENUM" -ne 0 ] && echo
		((LINENUM++))
		local FIELDNUM=0
		for TEXT in $LINE; do
			[ -z "$TEXT" ] || echo $GREEN${FIELDS[$FIELDNUM]}: $NC$TEXT
			((FIELDNUM++))
		done
	done
}

function search {
	DATA=$(gp)
	IFS="$IFS_ORIG"
	#Find a match that contains all search words in any order
	for WORD in $SEARCH; do
		DATA=$(grep -Pi "$WORD" <<< $DATA)
	done
	formatEntry <<< $DATA
}

function checkFresh {
	[ $(find "$GPDATA" -newermt '-1 seconds'| wc -l) -gt 0 ] && FRESH=yes
}

FRESH=""

if [ ! "$CACHED" ]; then
	echo "Downloading GreenPages Data. Please wait..."
	getData
	if [ ! "$CACHED"  ]; then
		clearLastLine
		echo $RED"Could not download GreenPages Data. Connect to VPN and try again."$NC
		exit 1
	fi
	clearLastLine
else
	getData &
	PID=$!
	I=0; while [ $I -lt $UPDATE_TIMEOUT ]; do
		echo -n $LBLACK.
		kill -0 $PID 2>&- || break
		((I++))
		sleep 0.01
	done
	echo $NC
	checkFresh
	clearLastLine
	getFields
	search
	if [ $FRESH ]; then
		echo $GREEN"... Online ..."
	else
		echo $RED"... Offline ..."
	fi
	echo -n $NC
fi
