#!/usr/bin/env bash
#This is a simple greenpages cli client with offline capability

. colors.sh

GPURI="http://gpapi.parkdalemills.com/cli"
GPDATA=~/.greenpages

FRESH=""
FIELDS=()
SEARCH=$*
IFS_ORIG="$IFS"

function getFields {
	read -r -a HEADER <<< $(head -n 1 "$GPDATA")
	IFS='|' 
	for FIELD in $HEADER; do
		FIELDS+=($FIELD)
	done
	export FIELDS
}

function getData {
	curl -s "$GPURI" -o "$GPDATA" 2>$- && FRESH=yes
}

function gp {
	tail -n +2 "$GPDATA"
}

function clearLastLine {
	tput cuu 1 && tput el
}

function formatEntry {
	local LINENUM=0
	IFS="|"
	while read LINE; do
		[ "$LINENUM" -ne 0 ] && echo
		((LINENUM++))
		local FIELDNUM=0
		for TEXT in $LINE; do
			[ -z "$TEXT" ] || echo $GREEN${FIELDS[$FIELDNUM]}: $NC$TEXT
			((FIELDNUM++))
		done
	done
}

function search {
	DATA=$(gp)
	IFS="$IFS_ORIG"
	#Find a match that contains all search words in any order
	for WORD in $SEARCH; do
		DATA=$(grep -Pi "$WORD" <<< $DATA)
	done
	formatEntry <<< $DATA
}

if [ ! -f "$GPDATA" ]; then
	echo "Downloading GreenPages Data. Please wait..."
	getData
	if [ ! $FRESH ]; then
		clearLastLine
		echo "Could not download GreenPages Data. Connect to VPN and try again."
		exit 1
	fi
	clearLastLine
fi

getFields
search
getData &
