#!/bin/bash
SEARCH="$1"
[ -z "$SEARCH" ] && SEARCH="^"
MATCHES=$(gam print users 2>/dev/null | grep -v '^primaryEmail$' | grep -Pi "$SEARCH")
MATCHNUM=$(echo -n "$MATCHES" | grep "^" -c)

[ -z "$SEARCH" ] || SPHRASE="for '$SEARCH'"
[ $MATCHNUM -eq 0 ] && echo No Matches $SPHRASE
[ $MATCHNUM -eq 1 ] && gam info user "$MATCHES" | ack --passthru -i "Last login time: (.*)|($SEARCH)"
[ $MATCHNUM -gt 1 ] && echo "$MATCHES" #| ack --passthru -i "$SEARCH"

