#!/usr/bin/env bash

#ip_subnet_valiade <CIDR notation subnet mask>
#Returns the subnet if it's valid
#Returns nothing and exits with error status 1 if the subnet is invalid
#This script validates IPs from 0.0.0.0 to 255.255.255.255 and masks from 0 to 32

SUBNET="$1"
IFS='/' read -r IP MASK <<< $SUBNET

[[ "$MASK" =~ ^[0-9]+$ ]] && [ "$MASK" -ge 0 ] && [ "$MASK" -le 32 ] || exit 1

[[ "$IP" =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]] || exit 1

echo $SUBNET
