#!/usr/bin/env bash

#ip_valiade <ip address>
#Returns the IP address if it's valid
#Returns nothing and exits with error status 1 if the IP is invalid
#This regex validates IPs from 0.0.0.0 to 255.255.255.255

IP="$1"

[[ "$IP" =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]] || exit 1

echo $IP
