#!/bin/env bash

TARGET=/usr/local/bin

if [ ! -d $TARGET ]; then
	echo $TARGET does not exist. Exiting!
	exit
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

shopt -s extglob #Enable glob exclusions

CMD="ln -f -s $DIR/!(LICENSE) $TARGET"
echo "I am going to execute the following commands:"
echo $CMD

while [[ ! "$GO" =~ ^(y|n)$ ]]; do
	echo -n "Write config? (y/n)"
	read GO
done
[ "$GO" != "y" ] && echo "You entered '$GO'. Exiting install..." && exit
echo "Installing..."
$CMD
echo "Done!"

