#!/usr/bin/env bash

TARGET=/usr/local/bin

if [ ! -d $TARGET ]; then
	echo $TARGET does not exist. Exiting!
	exit
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

UPDATE="sudo git -C '$DIR' pull"

shopt -s extglob #Enable glob exclusions

for FILE in $(ls "$DIR"); do
	[ "$FILE" != "README.md" ] && [ "$FILE" != "LICENSE" ] && CMD="${CMD}sudo ln -f -s '$DIR/$FILE' '$TARGET/$FILE'"$'\n'
done

echo "I am going to execute the following commands:"
echo "$UPDATE"
echo "$CMD"

while [[ ! "$GO" =~ ^(y|n)$ ]]; do
	echo -n "Update and install? (y/n): "
	read GO
done
[ "$GO" != "y" ] && echo "You entered '$GO'. Exiting install..." && exit
echo "Updating..."
echo "$UPDATE" | bash
echo "Installing..."
echo "$CMD" | bash
