#!/usr/bin/env bash
MCAST_ADDR=224.0.2.60
MCAST_PORT=4445
BCAST_ADDR="$1"
MCAST_IF=$(ip route show to match $MCAST_ADDR | cut -d' ' -f5)
LAN_ADDR=$(ip -f inet -o addr show $MCAST_IF|cut -d\  -f 7 | cut -d/ -f 1)
ME=$(basename $0)

if [[ ! "$BCAST_ADDR" =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]]; then
	echo "$ME will continue to proxy traffic for 1 minute. It is mean to be ran every minute as a cron job."
	echo "Usage:"
	echo "$ME <broadcast IP>"
	echo "$ME 192.168.3.255"
	echo "$ME 255.255.255.255"
	exit 1
fi

sudo timeout -k1 59 socat UDP4-RECV:$MCAST_PORT,bind=$MCAST_ADDR,ip-add-membership=$MCAST_ADDR:$MCAST_IF,reuseaddr,range=$LAN_ADDR/32 UDP4-SENDTO:$BCAST_ADDR:$MCAST_PORT,broadcast

exit 0
