#!/usr/bin/env bash

#Kill all background processes when this wrapper is killed
trap 'kill $(jobs -p) 2>/dev/null' EXIT INT

#Iterate through given file
for file in "$@"
do
  #Tail each one
	tail -F $file &
done

#Wait until wrapper is terminated (CTRL-C)
wait
