#!/usr/bin/env bash

NAME="$*"
SCRIPT="$(basename "$0")"

function help() {
	echo "$SCRIPT creates a new starter bash script"
	echo "Usage:"
	echo "  $SCRIPT script_name"
	echo
	exit 1
}


[ -z "$NAME" ] && help
[ -e "$NAME" ] && echo "$NAME already exists. Exiting." && exit 1

cat << 'EOTEMPLATE' > "$NAME"
#!/usr/bin/env bash

SCRIPT="$(basename "$0")"

function help() {
	cat <<-EOF

		$SCRIPT $_description_of_functionality_
	
		Usage example:
		  $SCRIPT $_example_usage_

	EOF
	exit 1
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-v|--param-with-value)
	PARAM_VALUE="$2"
	shift # past argument
	shift # past value
	;;
	-h|--help)
	help
	shift # past argument
	;;
	-p|--param-only)
	PARAM_ONLY="YES"
	shift # past argument
	;;
	*) # unknown option
	POSITIONAL+=("$1") # save it in an array for later
	shift # past argument
	;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

EOTEMPLATE

chmod +x "$NAME"
$EDITOR "$NAME"
