#!/usr/bin/env bash

NAME="$*"
SCRIPT_PATH="$(realpath "$0")"
SCRIPT="$(basename "$SCRIPT_PATH")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

[ -z "$EDITOR" ] && command -v vim >&- && EDITOR=vim
[ -z "$EDITOR" ] && command -v vi >&- && EDITOR=vi
[ -z "$EDITOR" ] && command -v nano >&- && EDITOR=nano

function help() {
	echo "$SCRIPT creates a new starter bash script"
	echo "Usage:"
	echo "  $SCRIPT script_name"
	echo
	exit 1
}


[ -z "$NAME" ] && help
[ -e "$NAME" ] && echo "$NAME already exists. Exiting." && exit 1

cat << 'EOTEMPLATE' > "$NAME"
#!/usr/bin/env bash

SCRIPT_PATH="$(realpath "$0")"
SCRIPT="$(basename "$SCRIPT_PATH")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

function help() {
	cat <<-EOF

		$SCRIPT $_description_of_functionality_
	
		Usage example:
		  $SCRIPT $_example_usage_

	EOF
	exit 1
} 

function on_exit() {
	: # Your cleanup code here
}
trap on_exit EXIT

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-v|--param-with-value)
	PARAM_VALUE="$2"
	shift # past argument
	shift # past value
	;;
	-h|--help)
	help
	shift # past argument
	;;
	-p|--param-only)
	PARAM_ONLY="YES"
	shift # past argument
	;;
	*) # unknown option
	POSITIONAL+=("$1") # save it in an array for later
	shift # past argument
	;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

EOTEMPLATE

chmod +x "$NAME"
$EDITOR "$NAME"
