#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 host [other options]"
  echo
  exit
fi

TARGETHOST=$1
shift

#With keyboard grabbing disabled
xfreerdp /scale-desktop:400 /smart-sizing /w:1920 /h:1080 /v:$TARGETHOST /sec:rdp $* -grab-keyboard
