#!/usr/bin/env bash

SCRIPTPATH="$(dirname $(realpath $0))"

site="$*"

. unifi_auth
. unifi_select_site "$site"

unifi_list_devices | jq -r '.data[] | "\(.ip)\t\(.mac)\t\(.name)\t\(.radio_table[0].channel)\t\(.radio_table[1].channel)"'
