#!/usr/bin/env bash

if [ -z "$unifi_username" ]; then
	if [ ! -t 1 ] || [ ! -t 0 ]; then
		# stdout isn't a terminal
		echo "There are no cached credentials. Please run '. unifi_auth' alone to cache them."
		return 2>&-
		exit 1
	fi

	>&2 echo "If you source this file you credentials will be cached in memory for this shell only"
	
	if [ -z $unifi_username ]; then
		>&2 echo -n 'Username: '
		read unifi_username
	fi
	
	>&2 echo -n 'Password: '
	read -s unifi_password
	>&2 echo
	>&2 echo

	export unifi_username
	export unifi_password
	export unifi_baseurl=https://unifi:8443
fi

