#!/usr/bin/env bash

SCRIPTPATH="$(dirname $(realpath $0))"

site="$*"

. unifi_auth
. unifi_select_site "$site"

unifi_list_sta | jq -r '.data[] | "\(.ip)\t\(.mac)\t\(.oui)\t\(.hostname)\t\(.essid)\t\(.bssid)\t\(.channel)\t\(.signal)\t\(.noise)\t\(.rssi)"'
