#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 host [other options]"
  echo
  exit
fi

host=$1
shift

java -jar /usr/share/vnc/classes/VncViewer.jar $1 ScalingFactor="FixedRatio" RemoteResize=0 $*
