#!/usr/bin/env bash

#RATIO=FixedRatio
RATIO=Auto

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 host [other options]"
  echo
  exit
fi

TARGETHOST=$1
shift

java -jar /usr/share/vnc/classes/VncViewer.jar $TARGETHOST ScalingFactor="$RATIO" RemoteResize=0 Shared=1 $*
