#!/usr/bin/env python
from bs4 import BeautifulSoup
from requests import get
from pushover import Client
from configparser import ConfigParser
from pathlib import Path
import re
import click
import sys
import datetime

priority=2
retry=180
expire=14400

urls = [
	"https://www.woot.com/",
	"https://www.woot.com/category/home",
	"https://www.woot.com/category/electronics",
	"https://www.woot.com/category/computers",
	"https://www.woot.com/category/tools",
	"https://www.woot.com/category/sport",
	"https://www.woot.com/category/wine",
	"https://www.woot.com/category/sellout"
]

config = ConfigParser()
config.read(Path.home() / '.pushover.ini')
token = config.get('PUSHOVER', 'token')
user = config.get('PUSHOVER', 'user')

def check_url(url, regex):
    html = get(url).content
    soup = BeautifulSoup(html, features="lxml")
    title = soup(class_="main-title")[0].text
    if re.match(re.compile(f'.*{regex}.*', re.IGNORECASE), title):
        Client(user, api_token=token).send_message(f'Woot has: {title}', title=f'Woot has: {title}', priority=priority, retry=retry, expire=expire, url_title=url, url=url)
        #print(title, url, user, token)

@click.command()
@click.argument('regex')
def check(regex):
    """Check woot categories for an item title matching <regex>"""
    for url in urls:
        check_url(url, regex)

if __name__ == '__main__':
    check()

